(define bitvector->string #f)
(define string->bitvector #f)
(define bitvector->integer #f)
(define integer->bitvector #f)
(define bitvector->bytevector #f)
(define bitvector->bytevector! #f)
(define bytevector->bitvector #f)
