(define bitvector->string #f)
(define string->bitvector #f)
(define bitvector->integer #f)
(define integer->bitvector #f)
(define make-bitvector/int-generator #f)
(define make-bitvector/bool-generator #f)
(define make-bitvector-accumulator #f)
