(define (make-bitvector/int-generator bvec)
  (lambda ()
    (let ((len (bitvector-length bvec))
          (i 0))
      (if (= i len)
        (eof-object)
        (let ((r (bitvector-ref/int i)))
          (set! i (+ i 1))
          r)))))

(define (make-bitvector/bool-generator bvec)
  (lambda ()
    (let ((len (bitvector-length bvec))
          (i 0))
      (if (= i len)
        (eof-object)
        (let ((r (bitvector-ref/bool i)))
          (set! i (+ i 1))
          r)))))

(define (make-bitvector-accumulator)
  (lambda (x)
    (let ((r '()))
      (if (eof-object? x)
        (reverse-list->bitvector r)
        (set! r (cons x r))))))
